'use strict';
const fs=require('fs');
const path=require('path');
const root=path.resolve(__dirname,'..');
const articles=require('../content/blog-articles.cjs').sort((a,b)=>b.published.localeCompare(a.published));
const site='https://yatogo.ru';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const org={"@type":"Organization","@id":`${site}/#organization`,name:'YATOGO',url:`${site}/`,logo:{"@type":"ImageObject",url:`${site}/assets/logo-mark.svg`},telephone:'+998501113939',email:'info.yatogo@gmail.com',sameAs:['https://t.me/anwaryul','https://wa.me/998501113939']};
const metrika=`<!-- Yandex.Metrika counter --><script>(function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)};m[i].l=1*new Date();for(var j=0;j<document.scripts.length;j++){if(document.scripts[j].src===r){return}}k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)})(window,document,'script','https://mc.yandex.ru/metrika/tag.js?id=113132820','ym');ym(113132820,'init',{ssr:true,webvisor:true,clickmap:true,referrer:document.referrer,url:location.href,accurateTrackBounce:true,trackLinks:true});</script>`;

function schema(a){const url=`${site}/blog/${a.slug}/`;return {"@context":"https://schema.org","@graph":[org,{"@type":"BlogPosting","@id":`${url}#article`,headline:a.title,description:a.description,datePublished:a.published,dateModified:a.modified,inLanguage:'ru',mainEntityOfPage:{"@id":`${url}#webpage`},author:{"@id":`${site}/#organization`},publisher:{"@id":`${site}/#organization`},image:`${site}/assets/og-cover.png`},{"@type":"WebPage","@id":`${url}#webpage`,url,name:a.shortTitle,isPartOf:{"@id":`${site}/#website`},about:{"@id":`${site}/#organization`},breadcrumb:{"@id":`${url}#breadcrumb`}},{"@type":"BreadcrumbList","@id":`${url}#breadcrumb`,itemListElement:[{"@type":"ListItem",position:1,name:'Главная',item:`${site}/`},{"@type":"ListItem",position:2,name:'Блог',item:`${site}/blog/`},{"@type":"ListItem",position:3,name:a.shortTitle,item:url}]},{"@type":"FAQPage",mainEntity:a.faq.map(([name,text])=>({"@type":"Question",name,acceptedAnswer:{"@type":"Answer",text}}))}]};}

function page(a){const canonical=`${site}/blog/${a.slug}/`;return `<!doctype html>
<html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<title>${esc(a.seoTitle)}</title><meta name="description" content="${esc(a.description)}"><meta name="robots" content="index,follow,max-image-preview:large"><meta name="theme-color" content="#0B7A5B"><link rel="canonical" href="${canonical}">
<meta property="og:type" content="article"><meta property="og:title" content="${esc(a.title)}"><meta property="og:description" content="${esc(a.description)}"><meta property="og:url" content="${canonical}"><meta property="og:site_name" content="YATOGO"><meta property="og:locale" content="ru_RU"><meta property="og:image" content="${site}/assets/og-cover.png"><meta property="article:published_time" content="${a.published}"><meta property="article:modified_time" content="${a.modified}"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${esc(a.title)}"><meta name="twitter:description" content="${esc(a.description)}"><meta name="twitter:image" content="${site}/assets/og-cover.png">
<script type="application/ld+json">${JSON.stringify(schema(a))}</script><link rel="icon" href="../../favicon.svg" type="image/svg+xml"><link rel="preload" href="../../assets/fonts/manrope-cyrillic.woff2" as="font" type="font/woff2" crossorigin><link rel="stylesheet" href="../../assets/css/fonts.css"><link rel="stylesheet" href="../../assets/css/blog.css">${metrika}</head>
<body><noscript><div><img src="https://mc.yandex.ru/watch/113132820" style="position:absolute;left:-9999px" alt=""></div></noscript><a class="skip-link" href="#article">Перейти к статье</a>
<header class="blog-header"><div class="blog-header__inner"><a class="blog-brand" href="/" aria-label="YATOGO — главная"><img src="../../assets/logo-mark.svg" alt=""><span>YATOGO</span></a><nav class="blog-nav" aria-label="Основная навигация"><a href="/">Главная</a><a href="/blog/">Блог</a><a href="/#contact">Контакты</a><a class="blog-nav__cta" href="/#contact">Оставить заявку</a></nav></div></header>
<main class="blog-shell"><nav class="breadcrumbs" aria-label="Хлебные крошки"><a href="/">Главная</a><span aria-hidden="true">→</span><a href="/blog/">Блог</a><span aria-hidden="true">→</span><span>${esc(a.shortTitle)}</span></nav>
<header class="blog-hero"><p class="eyebrow">${esc(a.eyebrow)}</p><h1>${esc(a.title)}</h1><p class="blog-lead">${esc(a.lead)}</p><div class="blog-meta"><span>Опубликовано: ${a.publishedText}</span><span>•</span><span>Обновлено: 5 октября 2026</span><span>•</span><span>Чтение: около ${a.read}</span></div></header>
<div class="article-grid"><article class="article" id="article"><div class="quick-answer"><strong>Короткий ответ</strong>${esc(a.quick)}</div>
<div class="article-visual" role="img" aria-label="${esc(a.visual.join(', '))}">${a.visual.map((x,i)=>`<div><span>${i+1}</span><strong>${esc(x)}</strong></div>`).join('')}</div>
<div class="facts">${a.facts.map(([k,v])=>`<div class="fact"><strong>${esc(k)}</strong>${esc(v)}</div>`).join('')}</div>
${a.sections.map(([id,title,html])=>`<h2 id="${id}">${esc(title)}</h2>${html}`).join('\n')}
<section class="cta-box"><h2>Получить план действий для вашей ситуации</h2><p>YATOGO сопровождает регистрацию и дальнейший запуск бизнеса в Узбекистане. Срок сопровождения — от 2 рабочих дней, стоимость рассчитывается индивидуально.</p><a class="button" href="/#contact" data-metrika-goal="cta_apply_click">Оставить заявку</a></section>
<section class="related"><h2>Читайте также</h2><ul>${a.related.map(([t,u])=>`<li><a href="${u}">${esc(t)}</a></li>`).join('')}</ul></section>
<section class="faq"><h2 id="faq-title">Частые вопросы</h2>${a.faq.map(([q,ans])=>`<details><summary>${esc(q)}</summary><p>${esc(ans)}</p></details>`).join('')}</section>
<section class="sources"><h2>Официальные источники</h2><ul>${a.sources.map(([t,u])=>`<li><a href="${u}" target="_blank" rel="noopener">${esc(t)}</a></li>`).join('')}</ul></section><p class="article-updated">Материал опубликован ${a.publishedText} и проверен 5 октября 2026 года. Информация носит справочный характер; требования и ставки могут меняться.</p></article>
<aside class="toc" aria-label="Содержание статьи"><strong>В статье</strong>${a.sections.map(([id,title])=>`<a href="#${id}">${esc(title)}</a>`).join('')}<a href="#faq-title">Частые вопросы</a></aside></div></main>
<footer class="blog-footer"><div class="blog-footer__inner"><span>© 2026 YATOGO</span><span><a href="/blog/">Все статьи</a> · <a href="/privacy/">Политика конфиденциальности</a> · <a href="mailto:info.yatogo@gmail.com">info.yatogo@gmail.com</a></span></div></footer></body></html>\n`;}

for(const a of articles){const dir=path.join(root,'blog',a.slug);fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'index.html'),page(a));}

const first={slug:'otkryt-ooo-v-uzbekistane',title:'Как открыть ООО в Узбекистане гражданину России в 2026 году',description:'ПИНФЛ, документы, адрес, директор, ЭЦП, банк, сроки и удалённая регистрация.',published:'2026-10-05',publishedText:'5 октября 2026'};
const all=[first,...articles].sort((a,b)=>b.published.localeCompare(a.published));
const indexSchema={"@context":"https://schema.org","@graph":[org,{"@type":"CollectionPage","@id":`${site}/blog/#webpage`,url:`${site}/blog/`,name:'Блог о регистрации бизнеса в Узбекистане',description:'Практические материалы YATOGO о регистрации и сопровождении бизнеса в Узбекистане.',inLanguage:'ru',publisher:{"@id":`${site}/#organization`}},{"@type":"ItemList",itemListElement:all.map((a,i)=>({"@type":"ListItem",position:i+1,url:`${site}/blog/${a.slug}/`,name:a.title}))}]};
const cards=all.map(a=>`<a class="article-card" href="/blog/${a.slug}/"><span class="article-card__tag">${a.publishedText}</span><h2>${esc(a.title)}</h2><p>${esc(a.description)}</p><span class="article-card__more">Читать материал →</span></a>`).join('\n');
const index=`<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>Блог о регистрации бизнеса в Узбекистане | YATOGO</title><meta name="description" content="Практические материалы YATOGO о регистрации ООО и ИП, ПИНФЛ, налогах, документах и банках для иностранцев в Узбекистане."><meta name="robots" content="index,follow,max-image-preview:large"><meta name="theme-color" content="#0B7A5B"><link rel="canonical" href="${site}/blog/"><meta property="og:type" content="website"><meta property="og:title" content="Блог о регистрации бизнеса в Узбекистане | YATOGO"><meta property="og:description" content="Понятные инструкции для иностранных учредителей и предпринимателей."><meta property="og:url" content="${site}/blog/"><meta property="og:image" content="${site}/assets/og-cover.png"><meta name="twitter:card" content="summary_large_image"><script type="application/ld+json">${JSON.stringify(indexSchema)}</script><link rel="icon" href="../favicon.svg" type="image/svg+xml"><link rel="preload" href="../assets/fonts/manrope-cyrillic.woff2" as="font" type="font/woff2" crossorigin><link rel="stylesheet" href="../assets/css/fonts.css"><link rel="stylesheet" href="../assets/css/blog.css">${metrika}</head><body><noscript><div><img src="https://mc.yandex.ru/watch/113132820" style="position:absolute;left:-9999px" alt=""></div></noscript><a class="skip-link" href="#main">Перейти к содержимому</a><header class="blog-header"><div class="blog-header__inner"><a class="blog-brand" href="/"><img src="../assets/logo-mark.svg" alt=""><span>YATOGO</span></a><nav class="blog-nav"><a href="/">Главная</a><a href="/blog/" aria-current="page">Блог</a><a href="/#contact">Контакты</a><a class="blog-nav__cta" href="/#contact">Оставить заявку</a></nav></div></header><main class="blog-shell" id="main"><nav class="breadcrumbs"><a href="/">Главная</a><span>→</span><span>Блог</span></nav><section class="blog-hero"><p class="eyebrow">Практика YATOGO</p><h1>Бизнес в Узбекистане: инструкции без лишней воды</h1><p class="blog-lead">ООО, ИП, документы, ПИНФЛ, налоги, банковские процедуры и удалённое сопровождение иностранцев. Изменяемые требования проверяем по официальным источникам.</p><div class="blog-meta"><span>10 подробных материалов</span><span>•</span><span>Обновлено 5 октября 2026</span></div></section><section><h2 class="section-title">Все материалы</h2><div class="article-list">${cards}</div></section></main><footer class="blog-footer"><div class="blog-footer__inner"><span>© 2026 YATOGO</span><span><a href="/privacy/">Политика конфиденциальности</a> · <a href="mailto:info.yatogo@gmail.com">info.yatogo@gmail.com</a></span></div></footer></body></html>\n`;
fs.writeFileSync(path.join(root,'blog','index.html'),index);

const urls=[['/',null],['/blog/','2026-10-05'],...all.map(a=>[`/blog/${a.slug}/`,a.modified||a.published])];
const sitemap=`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls.map(([u,d])=>`  <url>\n    <loc>${site}${u}</loc>${d?`\n    <lastmod>${d}</lastmod>`:''}\n  </url>`).join('\n')}\n</urlset>\n`;
fs.writeFileSync(path.join(root,'sitemap.xml'),sitemap);
console.log(`Built ${articles.length} articles, blog index and sitemap.`);
